name: Build BScript GUI

on:
  workflow_run:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt || echo "No requirements.txt"
      - name: Build Windows executable
        run: |
          pyinstaller --windowed --onefile bscript-gui.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: bscript-gui-windows
          path: dist/bscript-gui.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt || echo "No requirements.txt"
      - name: Build Linux executable
        run: |
          pyinstaller --windowed --onefile bscript-gui.py
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: bscript-gui-linux
          path: dist/bscript-gui
